version: '3'
services:

  tor:
    image: dperson/torproxy
    ports:
      - "8118:8118"
      - "9050:9050"
    networks:
      - backend

  mongodb:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    container_name: mongodb
    restart: unless-stopped
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: darkdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrawler  
    depends_on:
      - mongodb  
    command: python -u src/main.py
    environment:
      MONGODB_DATABASE: dark
      MONGODB_USERNAME: scrawler
      MONGODB_PASSWORD: scrawlerpassword
      MONGODB_HOSTNAME: mongodb
    volumes:
      - ./src:/app/src  
    networks:
      - backend
        
networks:
  backend:
    driver: bridge  

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local