version: '3'
services:

  tor:
    image: dperson/torproxy
    restart: unless-stopped
    hostname: tor-proxy
    ports:
      - "8118:8118"
      - "9050:9050"
    networks:
      - backend

  mongodb:
    image: mongo:4.0.8
    ports:
      - "27017:27017"
    container_name: mongodb
    hostname: mongo
    restart: unless-stopped
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: darkdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

  api-server:
    build:
      context: "./server"
      dockerfile: Dockerfile
    container_name: server  
    ports:
      - "5000:5000"
    networks:
      - backend
      # - client
    environment:
      CHOKIDAR_USEPOLLING: "true"   
    volumes:
      - type: bind
        source: ./server
        target: /app/server
    depends_on:
      - mongodb    

  web:
    build:
      context: ./scrawler
      dockerfile: Dockerfile
    container_name: scrawler  
    depends_on:
      - mongodb  
    command: python -u src/main.py
    environment:
      MONGODB_DATABASE: dark
      MONGODB_USERNAME: scrawler
      MONGODB_PASSWORD: scrawlerpassword
      MONGODB_HOSTNAME: mongodb
    volumes:
      - ./scrawler/src:/app/src  
    networks:
      - backend

networks:
  backend:
    driver: bridge  

volumes:
  mongodbdata:
    driver: local